/*
 * SPI_HO.c
 *
 *  Created on: Mar 21, 2024
 *      Author: natha
 */


#include "SPI_HO.h"
#include "stm32u5xx.h"

#include "stdint.h"
#include "stdio.h"

void SPI_Init(void)
{
	#define AF5 0x05
	RCC->AHB1ENR|=RCC_AHB2ENR1_GPIOAEN;
	RCC->APB2ENR|=RCC_APB2ENR_SPI1EN;
	GPIOA->MODER|=GPIO_MODER_MODE5_1|GPIO_MODER_MODE6_1|GPIO_MODER_MODE7_1;
	GPIOA->MODER&=~(GPIO_MODER_MODE5_0|GPIO_MODER_MODE6_0|GPIO_MODER_MODE7_0);
	GPIOA->OSPEEDR|=GPIO_OSPEEDR_OSPEED5|GPIO_OSPEEDR_OSPEED6|GPIO_OSPEEDR_OSPEED7;

	GPIOA->AFR[0]|=(AF5<<20)|(AF5<<24)|(AF5<<28);
	SPI1->CR2=0;
	SPI1->CR1=SPI_CR1_SSI|SPI_CR1_SPE;
	SPI1->CR1=SPI_CR1_SSI|SPI_CR1_SPE;
	SPI1->CFG1=SPI_CFG1_MBR_2;
	SPI1->CFG2=SPI_CFG2_SSM|SPI_CFG2_MASTER;

}


